spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Hello Baby - QA"
  contactDetails:
    name: "Shreya - QA"
    email: "shreya@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-6789