server:
  port: 8080
spring:
  application:
    name: AccountsApplication
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/accountsdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  config:
    import:
      - "application-qa.yml"
      - "application-prod.yml"
  profiles:
    active:
      - "qa"


build:
  version: "3.0"

accounts:
  message: "Hello Baby"
  contactDetails:
    name: "Priya Dhar - Developer"
    email: "priyadhar@gmail.com"
  onCallSupport:
  - (555) 555-1234
  - (555) 555-6789
